# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs: 
  build:

    runs-on: [windows-latest]

    steps:
    - uses: actions/checkout@v4

    - name: setup-msbuild
      uses: microsoft/setup-msbuild@v2

    - name: Setup NuGet
      uses: NuGet/setup-nuget@v2.0.0

    - name: Restore NuGet Packages
      run: nuget restore Ahorcado/Ahorcado.sln

    - name: Build the solution
      run: msbuild Ahorcado/Ahorcado.sln

  test:
    runs-on: [windows-latest]
    needs: build

    steps:
    - uses: actions/checkout@v4

    - name: Install .NET Framework 4.7.2 Developer Pack
      run: |
        Invoke-WebRequest -Uri https://download.visualstudio.microsoft.com/download/pr/6c3d4f6b-20f4-41ab-9d9d-b527a314087b/fcb0b48db69f98f17d3270c1d51a5925/NetFx472DeveloperPack.exe -OutFile NetFx472DeveloperPack.exe
        Start-Process -FilePath NetFx472DeveloperPack.exe -ArgumentList "/quiet", "/norestart" -Wait
        Remove-Item -Force NetFx472DeveloperPack.exe

    - name: Restore NuGet Packages
      run: dotnet restore Ahorcado/Ahorcado.sln

    - name: Run unit tests
      run: dotnet test Ahorcado/MSTest_Ahorcado_Frame/MSTest_Ahorcado_Frame.csproj --logger "trx" --results-directory "./test-results"
    
    - name: Upload test results
      uses: actions/upload-artifact@v3
      with:
        name: test-results
        path: ./test-results
